title: PizzaBluFX
url: https://pizzablufx.com
domain: pizzablufx.com

breakpoints:
  mobile: "810px"
  big: "2700px"

colors:
  background: "hsl(216deg 10% 10%)"
  text: "#ffffff"

navigation:
  - discord:
    name: "Support"
    url: "https://discord.gg/VMbRGbBeT6"
    icon: "fa-brands fa-discord"
  - youtube:
    name: "Videos"
    url: "https://www.youtube.com/channel/UCxOrC01PVvxYe_JzB9Q8nqQ"
    icon: "fa-brands fa-youtube"

navigation-basic:
  - home:
    name: "Home"
    url: "/index.html"
    icon: "fa-solid fa-home"

links:
  home: "/"
  eula: "/eula.html"
  privacy: "/privacy.html"
  discord: "https://discord.gg/VMbRGbBeT6"

plugins:
  - jekyll-redirect-from