title: PizzaBluFX
description: "The missing tools for DaVinci Resolve - trusted by over 7,000 video editors"
domain: pizzablufx.com

breakpoints:
  mobile: "810px"
  big: "2700px"

colors:
  background: "hsl(216deg 10% 10%)"
  text: "#ffffff"

navigation:
  - youtube:
    name: "Videos"
    url: "https://www.youtube.com/channel/UCxOrC01PVvxYe_JzB9Q8nqQ"
    icon: "fa-brands fa-youtube"
    external: true
  - discord:
    name: "Support"
    url: "https://discord.gg/VMbRGbBeT6"
    icon: "fa-brands fa-discord"
    external: true
  - faq:
    name: "FAQ"
    url: "/faq.html"
    icon: "fa-solid fa-book"

navigation-basic:
  - home:
    name: "Home"
    url: "/index.html"
    icon: "fa-solid fa-home"

links:
  home: "/"
  eula: "/eula.html"
  privacy: "/privacy.html"
  faq: "/faq.html"
  kofi: "https://ko-fi.com/pizzablu/"
  youtube: "https://www.youtube.com/channel/UCxOrC01PVvxYe_JzB9Q8nqQ"
  discord: "https://discord.gg/VMbRGbBeT6"
  bluesky: "https://bsky.app/profile/pizzablufx.com"
  twitch: "https://www.twitch.tv/p1zzablu"
  github: "https://github.com/PizzaBlu"
  portal: "https://www.creem.io/portal"
  mailto: "mailto://support@pizzablufx.com"

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

exclude:
  - server.sh
  - server.ps1
  